### ISSUE TITLE
Incorrect unit in Home Assistant Energy dashboard for GAS reading 

### ISSUE THREAD

**Issue by benek984** [HandyHat/ha-hildebrandglow-dcc#109]
**Describe the bug**
In home assistant energy dashboard under gas consumption I can see quite good value but incorrect unit. I have used Yearly usage as suggested in the configuration. 
**To Reproduce**

add GAS Yearly sensor to Energy Dashboard in Home assistant configuration

**Screenshots**
<img width="1440" alt="Fullscreen_30_12_2021__21_13" src="https://user-images.githubusercontent.com/62546477/147788602-0a940c9f-e6d5-4008-bf77-a2c2eb4ac585.png">

**Version**
What version of the integration and what version of Home Assistant are you running?
Latest version and latest version of Home Assistant 
**Debug log**
n/a
**Additional context**
n/a

**Comment by ColinRobbins** [comment]
Are you sure this is not just because it is playing catch-up, with the usage since the start of the calendar year?
Let it run for a day or so and see if it stabilises to a correct value.

**Comment by benek984** [comment]
It may be but when you look on the daily or yearly usage in Lovelace it reports it correctly (compared with Bright iOS app).
<img width="387" alt="Screenshot_30_12_2021__23_15" src="https://user-images.githubusercontent.com/62546477/147793940-412e2aa2-dfc4-4cb2-97bf-10f39f55a2b4.png">

**Comment by benek984** [comment]
@ColinRobbins you were right that was some caused by "first day" reading. all looks good now.
