### ISSUE TITLE
Actual meter reading?

### ISSUE THREAD

**Issue by EDIflyer** [HandyHat/ha-hildebrandglow-dcc#116]
Would it be possible to pull in the actual meter reading number for gas & electricity or is this not something that is provided via the Hildebrand Glow service?

**Comment by EDIflyer** [comment]
Ah,OK - that could make it tricky! I had assumed that would have been one of the first things they shared but if they don't provide it then not much you can do!

**Comment by HandyHat** [comment]
Unfortunately as described here: https://docs.glowmarkt.com/GlowmarktAPIDataRetrievalDocumentationIndividualUserForBright.pdf
this is not available via the DCC
