### ISSUE TITLE
Glow API data error Tarrif (list index out of range)

### ISSUE THREAD

**Issue by pete-leese** [HandyHat/ha-hildebrandglow-dcc#118]
Glow API data error (Electric Tariff Standing): (list index out of range)

Glow API data error (Gas Tariff Standing): (list index out of range)

Getting above errors in logs when integration starts, I also notice tariff information is not visible in Bright App, if it helps I am on octopus energy flexible tariff. 

Is there a way this can be pulled or manually entered to ensure accurate cost usage? 

I contacted Glow and this is what they said which does not make a lot of sense :) 

Our source of truth for pricing data is your meters and it is your energy supplier who sets the pricing data (standing charge and rate).

Your energy display may have correct costs of consumption while the Bright App does not because the display retrieves the calculated cost of consumption from the meter whereas Bright retrieves the standing charge and rate from the tariff field on your meter and then applies that to the consumption (which is how we support tariffs like Octopus Agile). Your supplier has probably set the cost of consumption at meter level but have not set the separate standing charge and rate with the different rates for the time of use.

**Comment by ColinRobbins** [comment]
This is a common error, and a FAQ in this integration.
You need to contact your energy company - they need to provide tariff information to the DCC.

**Comment by dgthomson** [comment]
Thanks for all the work that's being done here. A great and useful integration!

My G&E tariffs come up in HA as 'unknown'. I can set them manually but the value only sticks for 5 minutes. I guess this is as long as the next update comes round. As my energy company E.on is 💩maybe another solution is an option to switch off even trying to set the tariff sensors? Then any values I set myself will persist.

**Comment by ColinRobbins** [comment]
You need you energy company to fix it.  They are legally required to do so if you have a SMETS 2 meter.

In the mean time instead of setting manually, why not use an `input number` helper?   Then it will never get overridden.

**Comment by dgthomson** [comment]
Thanks @ColinRobbins

Following this up and as an observation, HA doesn't seem too fussed about `sensor.electric_tariff_rate` being `unknown`. If there has been a valid number in the sensor state at some point it'll use it for energy cost calculations. I've got nodered injecting a value into the sensor just once at startup and that seems sufficient, even though this integration resets it after 2 minutes.

**Comment by ColinRobbins** [comment]
That seems like a lot of hard work to use NodeRed to override a sensor from a 3rd party integration, when HA has a built in mechanism to create a static sensor, you can set via the GUI!

**Comment by dgthomson** [comment]
Yeah, fair enough. Nodered seemed more accessible than HA years back when I started this and it's just how its set up!

**Comment by HandyHat** [comment]
As of v1.0.0, the tariff sensors are disabled by default and so this error should no longer be encountered.
