### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by derekoharrow** [HandyHat/ha-hildebrandglow-dcc#126]
**Describe the bug**
The integration seems to no longer be connecting to the Glow API to retrieve data - it just errors in the HA log file.

Is it just me?

**Version**
Glow - v0.5.0
HA - 2022.2.0 and 2021.12.x

**Debug log**
Debug logging enabled, but no additional error messages shown other than:
```
2022-02-03 09:42:38 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hildebrandglow_dcc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-03 09:43:13 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform hildebrandglow_dcc is taking over 10 seconds.
2022-02-03 09:49:51 WARNING (SyncWorker_1) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 09:49:51 WARNING (SyncWorker_9) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 09:49:51 WARNING (SyncWorker_5) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 09:49:51 WARNING (SyncWorker_6) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-02-03 09:49:51 WARNING (SyncWorker_8) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by ColinRobbins** [comment]
There are ongoing issues at the Glow end.

https://forum.glowmarkt.com/index.php?p=/discussion/129/bright-outage-including-apis-and-mqtt#latest

**Comment by NickDevoctomy** [comment]
The end of that suggests it's working again, but certainly isn't for me.  It's very sketchy at the moment,

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:694
First occurred: 4 February 2022, 18:31:39 (75 occurrences)
Last logged: 15:31:40

Update of sensor.electric_consumption_today is taking over 10 seconds
Update of sensor.electric_consumption_year is taking over 10 seconds
Update of sensor.electric_cost_today is taking over 10 seconds
Update of sensor.electric_tariff_standing is taking over 10 seconds
```

**Comment by NickDevoctomy** [comment]
aah, there's 3 pages.  Hopefully they get it sorted soon...

**Comment by googanhiem** [comment]
Latest update shows this functionality is still down (though daily readings are still available) and a message in the thread seems to imply they may not bring this functionality to use half hourly data back, without the purchase of one of their CADs. 

`We are reviewing when/how/whether we will restore regular DCC refresh and will update when a decision has been made.`

I guess I understand them reversing giving this full API access away for free, as there are data costs... I just assumed they'd continue doing it to grow their brand recognition. 

I was looking to get their CAD once it was back in stock, but this outage and some of the comments in their support thread are a bit concerning (ie charging yearly for local access to their devices.. kinda defeats the purpose of having local access for me, ie avoiding the device going dumb if they ever shut down).

**Comment by googanhiem** [comment]
Bit off topic... I'm also trying out Greenely app, which seems pretty solid with the same hourly functionality.. some have even found you can [scrape their app](https://github.com/linsvensson/sensor.greenely) for hourly updates, but I haven't got it working yet.. might just be for Swedish customers. They have mentioned in the past they may make an API.

**Comment by NickDevoctomy** [comment]
That  sounds like terrible news, as they are out of stock of their CADs and I've been on a waiting list for a couple of months now.  I even had a discussion when one of them over email as to how they can offer it for free in the first place without selling our data.

**Comment by si458** [comment]
@ColinRobbins the API is still down - https://forum.glowmarkt.com/index.php?p=/discussion/comment/540#Comment_540
could we maybe modify the module to not check every 5 seconds?
as they have suggested we should only be querying the API every 30minutes

**Comment by NickDevoctomy** [comment]
can we do that via a configuration change? or does it need to be made in the plugin?

**Comment by NickDevoctomy** [comment]
![image](https://user-images.githubusercontent.com/13888247/152999638-720b7c23-d53a-4968-832d-23cb36e64529.png)

I'm going to change the sensor.py file in my local installation for now.

**Comment by si458** [comment]
> ![image](https://user-images.githubusercontent.com/13888247/152999638-720b7c23-d53a-4968-832d-23cb36e64529.png)
> 
> I'm going to change the sensor.py file in my local installation for now.

dont forget to restart HASS after changing the value

**Comment by ColinRobbins** [comment]
> @ColinRobbins the API is still down - https://forum.glowmarkt.com/index.php?p=/discussion/comment/540#Comment_540 could we maybe modify the module to not check every 2 minutes? as they have suggested we should only be querying the API every 30 minutes?

Your PR for this seems reasonable to me - need @HandyHat to come online a accept it.

Hoping https://github.com/HandyHat/ha-hildebrandglow-dcc/pull/80 can be accepted  too, as this will further reduce server load when tariff data is unavailable.

**Comment by xhemp** [comment]
Clive (technical person at Glow) on Glow's Forum said the following:
-
As things stand we ignore all but the first request every half hour - BUT I would still prefer if those calls were not even made - they are just chewing bandwidth and cpu for exactly zero gain for you and us.
-

I remember reading here that it's 6 calls for electricity and 6 for gas so if that's the case, we won't be able to retrieve much from the API if they ignore all but the first request every half hour or did I get that wrong?

**Comment by ColinRobbins** [comment]
It seems to be working for me now - glow have fixed it, without the need for code change.

**Comment by si458** [comment]
> It seems to be working for me now - glow have fixed it, without the need for code change.   Agree the proposed code above remains a useful enhancement, given the better info from Glow on how it works. 

My elec seems to be returning now for the past hour OK
(I have the interval set at 30mins)
But my gas isn't being returned still 
It hasn't updated in 2 hours but even then its the same value as this morning value?

Im Guessing they are still having a few issues

**Comment by googanhiem** [comment]
Yes, mine has also recently started up, including gas, nearing 24 hrs now.
I've also lowered my scan interval manually. @HandyHat could we approve #135 ASAP to save the Hildebrand people a little headache.

**Comment by ColinRobbins** [comment]
I recommend looking at https://github.com/HandyHat/ha-hildebrandglow-dcc/pull/138, as an alternate to 135, as it provides a more comprehensive solution to helping the folk at Hildebrand, using the recommendation of when to poll from the Glow forum, as well as backing of polling for tariff data, if the data is not available.

**Comment by HandyHat** [comment]
Hey all, apologies for the delay. Just looking at this now - as pointed out, simply increasing the polling interval will often mean data is out of date. I think the solution in #136 and #138 is going to be the best one, so I'll be testing that before releasing it, most likely later today. Thanks for all your input, both here and on the glow forums!

**Comment by si458** [comment]
> I recommend looking at https://github.com/HandyHat/ha-hildebrandglow-dcc/pull/138, as an alternate to 135, as it provides a more comprehensive solution to helping the folk at Hildebrand, using the recommendation of when to poll from the Glow forum, as well as backing of polling for tariff data, if the data is not available.

@ColinRobbins I've applied the patch #138 and it does seem to be working including the unavailable for my gas tariffs 
But I through it would randomise the times every 30mins?
Mine seems to be calling at exactually 03mins and 33mins every hour?

**Comment by ColinRobbins** [comment]
The randomisation is the same behaviour as before the update.
The update cycle (as configured) runs every 5 minutes.  Exactly when this occurs will be based on when you start HA (hence the Random element of when HA starts).  If you start HA at 12:31.25,  then the integration will run at approx 01.25 and 31.25 every hour.

I don’t think the Hildebrand folk need randomisation from every HA instance.
Rather, they need randomisation across the installed base, so not everyone hits the server at the same time.   The randomisation from HA startup time will achieve this -  not everyone will start their HA at the same time.

HA does not give (as far as I know) any mechanism for an update to add a random element to the timing.   Doing it in the update cycles itself via sleeps causes issues, due the HA expectation that the update cycle does not block (even if using asyncio).  Based on my argument above, I believe it would be pointless anyway.

**Comment by si458** [comment]
@ColinRobbins ah right OK no worries my bad haha

**Comment by HandyHat** [comment]
Hey all, thank you for your thoughts. I'm going to go ahead and close this issue, as the original problem has been solved.

I have some further suggestions on how to edit the integration to reduce stress on Hildebrand servers, and I would love to get the community's thoughts in the discussion: https://github.com/HandyHat/ha-hildebrandglow-dcc/discussions/191
