### ISSUE TITLE
Unable to install into Home Assistant

### ISSUE THREAD

**Issue by craggus2000** [HandyHat/ha-hildebrandglow-dcc#132]
**Describe the bug**
Doesn't appear in the HA integrations list to install.
Automatic install of the repository via HACS and manual install have both been tried and failed.
Other integrations thru HACS have installed fine.

**To Reproduce**
Steps to reproduce the behaviour:

Followed instructions as supplied in readme.md

**Expected behaviour**
To be able to install the integration

**Screenshots**
N/A

**Version**
What version of the integration and what version of Home Assistant are you running?
0.5.2 and HA 2022.2.3

**Comment by craggus2000** [comment]
This is now working. It just took a few hours to appear.

**Comment by HandyHat** [comment]
Duplicate of #34
