### ISSUE TITLE
Issue / Bug Roll Up

### ISSUE THREAD

**Issue by ColinRobbins** [HandyHat/ha-hildebrandglow-dcc#137]
There have been a number of issue reports and PRs recently, but @HandyHat is not currently active.

We have no idea of @HandyHat personal circumstances, and fundamentaly hope they are OK, and will be able to accept a PR soon.

This issue, and associated PR is a roll up of issues, so when @HandyHat come online it will be easy for them to trace what needs doing.

# Issues resolved

* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/55 - reduces the number of lookup, by backing of unceassary calls to the API
* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/78 - better error handling for a DCC issue
* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/117 - better error handling
* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/118 - better error handling
* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/123 - based on information from Glow duing the outage, the number of unnecassary calls to the API have been reduced.
* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/126 - based on information from Glow duing the outage, the number of unnecassary calls to the API have been reduced.

# PR Roll up
This PR contains a roll up of the following PRs, that could be closed if the PR accepted.
* https://github.com/HandyHat/ha-hildebrandglow-dcc/pull/77 - alternative solution implemented  - as discussed in thread
* https://github.com/HandyHat/ha-hildebrandglow-dcc/pull/135 - alternative solution implemented.   Rather than set the time to 30 minutes.   Run it every 5 minutes, but only call glow API if between 00 and 05 or 30 and 35 minutes past the hour - as advised on [Glow forum](https://forum.glowmarkt.com/index.php?p=/discussion/comment/544/#Comment_544).
* https://github.com/HandyHat/ha-hildebrandglow-dcc/pull/136 - alternative solution implemented.   Rather than set the time to 30 minutes.   Run it every 5 minutes, but only call glow API if between 00 and 05 or 30 and 35 minutes past the hour - as advised on [Glow forum](https://forum.glowmarkt.com/index.php?p=/discussion/comment/544/#Comment_544).

# Using the PR prior to @HandyHat merging.
The simplest method would be to copy  this version of [sensor.py](https://github.com/ColinRobbins/ha-hildebrandglow-dcc/blob/dev/custom_components/hildebrandglow_dcc/sensor.py) (Make sure you use [this version](https://github.com/ColinRobbins/ha-hildebrandglow-dcc/blob/dev/custom_components/hildebrandglow_dcc/sensor.py), from the `dev` branch, and not from the `main` branch) to `custom_components/hildebrandglow_dcc` and restart HA.
Previous attempts to get HACS to use a forked branch caused lots of issues, and lots of tidying up when @HandyHat was able to accept the PR.    
We can look at this in time, if @HandyHat does not come back online in the near future.

**Note**:  When you restart, it can take upto 5 minute for data to pull through.  Please give it time before raising issues saying you have no data.

**Tariff Data**:  If you are no seeing Tariff data - check the Glow APP.    If there in not data in Glow, do not report an error here - this is nothing this Integration can do - you need to report the issue to your energy provider.

# Issues that cloud probably be closed...
* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/59 - This data is already available.  Suggest issue is closed. 
* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/83 - updates are provided every 30 minutes.   Suggest issue is closed.
* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/110 - Data is available, can be configured. Suggest issue is closed.
* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/116 - I don't think this is possible.  Suggest issue is closed

# Issue to keep open
* https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/99 - this needs some work in the initialision code.  Not clear how many people needed this.   Keep open as a feature request.

**Comment by HandyHat** [comment]
Apologies, been a bit busy so haven't been able to do a lot of development. I've been trying to catch up over the last day or so after the glow issues, so this is really helpful! I'll be merging some PRs later today

**Comment by ColinRobbins** [comment]
The current version in HACS should work.
The updates are to provide better error handling if (when) the Glow API breaks again.
Unless you needed the fixes for some reason, I suggest using the current version.

Hopefully @HandyHat will conclude their testing and make a new release soon.

**Comment by Davecl** [comment]
Thanks, I'll continue with the HACS version then

**Comment by ColinRobbins** [comment]
@HandyHat have you been able to consider this PR?
Rolling it out will reduce the load on the Glow API, hopefully making the API more reliable for all of us.

**Comment by RCGrahamWilmott** [comment]
Has a version (v0.6.0?) with these fixes been released? I'm still on v0.5.2 and not sure why it is not updating...

**Comment by ColinRobbins** [comment]
No.  @HandyHat are you able to make a release so everyone gets updates via HACS.
