### ISSUE TITLE
Stopped working 9am 16 Feb 2022 log warnings

### ISSUE THREAD

**Issue by thorrrr** [HandyHat/ha-hildebrandglow-dcc#147]
**Describe the bug**
NO data coming through as of 9am yesterday 16 Feb

**To Reproduce**
Easy look at logs and Energy Page no data

**Expected behaviour**
To show data 

**Screenshots**
Added

**Version**
## System Health

version | core-2022.2.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4854
Installed Version | 1.22.0
Stage | running
Available Repositories | 977
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 16.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Check Home Assistant configuration (3.10.0), SSH & Web Terminal (10.0.2), Home Assistant Google Drive Backup (0.105.2), Studio Code Server (4.1.0), MariaDB (2.4.0), InfluxDB (4.3.0), Grafana (7.4.1), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 16
views | 75
mode | storage

</details>

**Debug log**
https://0bin.net/paste/IA+tJHj1#G7AFdoU5I0K0FZeY2bMHNk+9LZuQHQiFpuvqqhCl0WB

**Additional context**
![msedge_Energy_–_Home_Assistant_and_15_more_pages_-_Person_2022-02-17_08 58 54](https://user-images.githubusercontent.com/8170673/154441250-f66b5810-1570-40c0-8dd7-1c09dcbb8462.jpg)
![msedge_Energy_–_Home_Assistant_and_15_more_pages_-_Person_2022-02-17_08 59 32](https://user-images.githubusercontent.com/8170673/154441254-910d41c7-7ec1-4fbf-bded-c7af9e655809.jpg)
![msedge_Configuration_–_Home_Assistant_and_15_more_pages_-_2022-02-17_08 58 27](https://user-images.githubusercontent.com/8170673/154441256-78606484-d184-439c-9725-36d2177080e9.jpg)

**Comment by ColinRobbins** [comment]
Problem is the interfaces between Glow and DCC.
Nothing this integration can do, but wait for Glow to fix it.

**Comment by thorrrr** [comment]
HI Colin 
When i check my Bright app data is flowing no issues very weird it was finally working with no issues.
Seems a very flaky connection i hope they don’t pull it.

**Comment by gedger** [comment]
I'm in the same situation but by Bright app has-stopped updating as well. I've put a post in the bright forum as well.

**Comment by thorrrr** [comment]
Mine has now :(

**Comment by thorrrr** [comment]
Started working then stopped with logs 
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:96
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:22:15 (2 occurrences)
Last logged: 16:22:15

[140320809551664] Received invalid command: energy/info

**Comment by ColinRobbins** [comment]
This log line above does not come from this intergation.

There will be no logging from this integration, because the intergation is working.
The integration contacts GLow ans says give me the latest meter reading.    Glow returns the data it has.
The problem in DCC are not feeding Glow the lastest data - so as far as Glow is concerned no new electrictiy/gas has been used, so Glow returns the most recent reading it has.

This is why your sensors show "data" - the last reading that was taken.

If the HA to Glow API failed, the Hildebrand component would log, and the sensors show "unavailable".

**Comment by si458** [comment]
this should be fixed now,
there support emailed me saying the was a boo boo in the system which they have fixed,
its been working fine for a few days now for me :)

**Comment by thorrrr** [comment]
yep same here i wil close it now thank you for your help
