### ISSUE TITLE
Split electricity tariffs

### ISSUE THREAD

**Issue by zandeez** [HandyHat/ha-hildebrandglow-dcc#177]
Hi, 

I was wondering if it were possible to query the split (Economy 7, etc) tariff times from the glow API. They appear in the Bright app.

It would be good to be able to use that to trigger high-energy appliances to run during the cheap period.

**Comment by ColinRobbins** [comment]
I believe it should do.   The tariff displayed, should be the current tariff.
You should then be able to run an automation when the tariff changes.
Not tested it however, as I only have a single tariff myself.

**Comment by zandeez** [comment]
I will test and let you know!
