### ISSUE TITLE
Pull through of historical data?

### ISSUE THREAD

**Issue by viking2010** [HandyHat/ha-hildebrandglow-dcc#188]
Hi,

The Hildebrand Bright app allows you to look back through at least 12 months worth of energy data from Gas/Electricity usage. It doesn't look like at present, that the integration pulls through any historical data. Is it feasible to pull down this historical usage information so it could be imported in to HA?

**Comment by HandyHat** [comment]
If by historical data you mean having that data show up in the energy dashboard, unfortunately this is not possible because Home Assistant does not allow data to be backdated

**Comment by viking2010** [comment]
Ahh ok, thank you for explaining. Happy to close this off now.

**Comment by viking2010** [comment]
Happy to close this off after explanation that historical data can't be inserted into HA.
