### ISSUE TITLE
Final data update of the day

### ISSUE THREAD

**Issue by j1mco** [HandyHat/ha-hildebrandglow-dcc#198]
The last 30 minutes of data is missing from the day due to polling times.  May I suggest one final update is triggered just before midnight too to complete the day's data as close as possible?

**Comment by HandyHat** [comment]
The update would have to be after midnight, but yes this is being worked on - see: https://github.com/HandyHat/ha-hildebrandglow-dcc/discussions/191

**Comment by andrewjhp** [comment]
Any update on this? I love this integration but the data is always out as a result of this.
