### ISSUE TITLE
Outdated Tarrifs

### ISSUE THREAD

**Issue by paulgbrichardson** [HandyHat/ha-hildebrandglow-dcc#228]
Given the wonderful energy cap increase /s my tarrif has naturally increased.  This isn't reflected in Home Assistant.  Is this an issue with my provider (Octopus), or a bug within the Add-on?  Any way for me to troubleshoot?

**Comment by Davecl** [comment]
Is your new tarrif showing in the bright app?
If not then it suggests Octopus' fault.
If yes then it suggests the integration.
My new tariffs showed immediately in both Bright and HA
