### ISSUE TITLE
Cant get entities to show up in Energy panel

### ISSUE THREAD

**Issue by mcc05** [HandyHat/ha-hildebrandglow-dcc#235]
Hi I've put this integration in all seems to work fine in getting data from bright. added the two year figures into logging but can't seen to get the entities to show up in the energy panel for selection any help would be great 
Mark HA 2022.6.7

**Comment by mcc05** [comment]
sorry started to show after logger ran for a few minutes

**Comment by mcc05** [comment]
all good

**Comment by HandyHat** [comment]
No worries!
