### ISSUE TITLE
Entities not available 

### ISSUE THREAD

**Issue by tungmeister** [HandyHat/ha-hildebrandglow-dcc#236]
**Describe the bug**
all my entities are showing as unavailable however all data is available in the app - I've readded the integration and was able to login without issue however the problem remains.

**To Reproduce**
Steps to reproduce the behaviour:

1. setup integration

**Expected behaviour**
entities should be available 

**Screenshots**
![image](https://user-images.githubusercontent.com/127809/176125629-4029fc21-aed3-4598-9dc8-79b2fd3b747e.png)

**Version**
6.0 2022.6.7

**Debug log**
```
2022-06-28 08:54:58 DEBUG (SyncWorker_2) [custom_components.hildebrandglow_dcc.glow] get 1: (https://api.glowmarkt.com/api/v0-1/resource)
2022-06-28 08:56:55 DEBUG (SyncWorker_7) [custom_components.hildebrandglow_dcc.glow] Post 1: (https://api.glowmarkt.com/api/v0-1/auth)
2022-06-28 08:56:55 DEBUG (SyncWorker_7) [custom_components.hildebrandglow_dcc.glow] Invalid data: {'valid': False}
2022-06-28 08:57:02 DEBUG (SyncWorker_8) [custom_components.hildebrandglow_dcc.glow] Post 1: (https://api.glowmarkt.com/api/v0-1/auth)
2022-06-28 08:57:02 DEBUG (SyncWorker_2) [custom_components.hildebrandglow_dcc.glow] get 1: (https://api.glowmarkt.com/api/v0-1/resource)
```

**Comment by jouster1974** [comment]
having same issue for past two days now

**Comment by Davecl** [comment]
It's done this a few times.. it's usually not the integration but the servers.. usually comes back after a couple of days

**Comment by kevspence** [comment]
@Davecl but why would entities work in other dashboards but not be available in Energy dashboard?

**Comment by tungmeister** [comment]
Mine have been unavailable since 22/06.

**Comment by rdbarry** [comment]
Having same issue. No data for previous 3 days

**Comment by ColinRobbins** [comment]
If you restart HA, the entries will shown as unavailable until a successful data reading is made.   With the unreliability of the API, it can take several hours after a restart for data to appear.

**Comment by kevspence** [comment]
@ColinRobbins That isn't the issue. The data is available to HA as I can see it in my own dashboards. It just that the entities can't be selected any more in the default Energy Dashboard. I've restarted， upgraded versions but this has made no difference.

**Comment by ColinRobbins** [comment]
Do any errors show up if you go to the developer tools / statistics page?
Sometimes HA will show why stats have stoped being generated, and offer a ‘fix issue’.

**Comment by jouster1974** [comment]
I've also had mine stop around late June and it has never returned...anything I can do to get these back...as did find them quite useful

**Comment by ColinRobbins** [comment]
> I've also had mine stop around late June and it has never returned...anything I can do to get these back...as did find them quite useful

Have you tried the solution posted above?

**Comment by jouster1974** [comment]
no...all are showing as fine in integration (apart from tariff ones which Im fine with)

![image](https://user-images.githubusercontent.com/15368005/183073001-305dd6c7-84fc-446c-96c8-8575fe657ac9.png)

but the two electric ones (for example) show no possible errors/fixes

![image](https://user-images.githubusercontent.com/15368005/183073375-4c2f8e2d-fb7c-496e-8317-0e531c4bda67.png)

**Comment by ColinRobbins** [comment]
Do the electric sensors show data if you look at them in history?

**Comment by jouster1974** [comment]
no  if i look at the sensors historically I see zero...but if i look at energy dashboard, I can see usage readings up to 26th June

![image](https://user-images.githubusercontent.com/15368005/183120855-20f0f8d1-5eb6-4293-8497-950de4521940.png)


![image](https://user-images.githubusercontent.com/15368005/183120911-9353598a-b500-4d84-a475-fa16ef206af3.png)

**Comment by ColinRobbins** [comment]
Do you see any data in the Hildebrand Glow App?

**Comment by ryan-exley** [comment]
Any update on this?

I have just  installed the integration as per instructions and all my entities are unavailable

@ColinRobbins as per your question yes i can see the data in the app

**Comment by ColinRobbins** [comment]
@ryan-exley there are several different issues above.   What are you exact symptoms.  What do you see in the home assistant logs?  Have is ever worked?

**Comment by craigclarksw** [comment]
After adding the itegration, and seeing all of the entities as "unavailable". the next morning I could see all of the data being pulled correctly.

**Comment by ryan-exley** [comment]
@ColinRobbins thanks for replying, i have been away so sorry for not replying sooner 

My experience is the same as @craigclarksw, after returning from holiday everything is working as expecetd

**Comment by HandyHat** [comment]
This should no longer occur with v1.0.0 of the integration. If this issue persists, please say!
