### ISSUE TITLE
Daylight Savings Time

### ISSUE THREAD

**Issue by AtomBrake** [HandyHat/ha-hildebrandglow-dcc#238]
Hi,

I've noticed that all of my data is 1 hour out (energy used between 7pm and 8pm BST is showing up as being used between 8pm and 9pm, and 0 energy used between midnight and 1am) - I suspect this is because HA is recognising daylight savings time, but the smart meters are not?

Thanks

Tom

**Comment by systeq** [comment]
Yes it is daylight savings time, if you wait a few months the problem will be resolved :)

It's not an issue with the integration, it's the metering system itself. It uses UTC all year round.

**Comment by ColinRobbins** [comment]
The integration should cope with the UTC/DST conversion.
The delay is because the Glow API presents data 30 minutes delayed.
They also implement some form of rate limiting, so sometime you only get an update once per hour.

**Comment by ColinRobbins** [comment]
The code makes a UTC/DST calculation [glow.py line 139](https://github.com/HandyHat/ha-hildebrandglow-dcc/blob/main/custom_components/hildebrandglow_dcc/glow.py#L139).

it’s working correctly for me…
![6DF9F848-6F6F-462D-AD79-347EA2F465AC](https://user-images.githubusercontent.com/13466873/179609869-8c4227eb-b2e1-42ec-9a5c-5af568904ad7.jpeg)

**Comment by HandyHat** [comment]
The library that this integration uses as of v1.0.0 should account for the shift in daylight savings and so this issue should not occur any more. If it persists, please say!
