### ISSUE TITLE
Periodic data fetch error

### ISSUE THREAD

**Issue by SGXander** [HandyHat/ha-hildebrandglow-dcc#242]
Hi,
I'm seeing this in the logs and a few data points missing corresponding to the entries:
low response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/47c7c371-c420-412f-a0b6-3897b5fdad55/readings?from=2022-01-01T00:00:00&to=2022-07-26T23:59:59&period=P1Y&offset=-60&function=sum)
Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/47c7c371-c420-412f-a0b6-3897b5fdad55/tariff)
Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/8a05a71f-9e0b-4c67-8eb5-d75f89c75086/readings?from=2022-07-26T00:00:00&to=2022-07-26T23:59:59&period=P1D&offset=-60&function=sum)
Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/47c7c371-c420-412f-a0b6-3897b5fdad55/readings?from=2022-07-26T00:00:00&to=2022-07-26T23:59:59&period=P1D&offset=-60&function=sum)
Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/28b080e5-4da4-4fa4-bc56-b5f031af29a1/readings?from=2022-07-26T00:00:00&to=2022-07-26T23:59:59&period=P1D&offset=-60&function=sum)

**Comment by ColinRobbins** [comment]
Yes, this is a problem with the instablity of the Glow API.   The intgration is reporting the error from the Glow API.

**Comment by thorrrr** [comment]
Same issue reported 100's times a day.
WIll this be feed back to Glow?

**Comment by Jealy91** [comment]
Also getting this error and very patchy data, will getting one of their devices to get the data locally resolve this or does it still rely on their API?

**Comment by Eddie46848** [comment]
I get this every hour now.

**Comment by DanDon** [comment]
I'm getting this every few minutes and all of the sensors are unavailable except 2. Sometimes just 1.

Something has changed either HA end in an update or Glow end in the api???

**Comment by HandyHat** [comment]
This should not occur as of v1.0.0
