### ISSUE TITLE
APP_ID conflict

### ISSUE THREAD

**Issue by harveyorg** [HandyHat/ha-hildebrandglow-dcc#252]
Looks like APP_ID is reserved.

I remained it to GLOW_APP-ID in all places and seems to have fixed it.

**Comment by ColinRobbins** [comment]
Where are you seeing this error?
I’m running the latest HA beta, and don’t see the issue.

**Comment by harveyorg** [comment]
I was installing for the first time. So, maybe it's part of code which only runs as part of initial setup.
As I said renaming all instances of APP_ID to GLOW_APP_ID fixed that issue.
