### ISSUE TITLE
Seems odd to put a `Dict[str,Any]` into a string

### ISSUE THREAD

**Issue by HarvsG** [HandyHat/ha-hildebrandglow-dcc#255]
https://github.com/HandyHat/ha-hildebrandglow-dcc/blob/0b58ab9974f02edc2781d32a83fb9c8d6b567244/custom_components/hildebrandglow_dcc/glow.py#L96-L104

**Comment by HandyHat** [comment]
This code has been scrapped as of v1.0.0.
