### ISSUE TITLE
Energy Data no longer showing after 10 Oct after latest update

### ISSUE THREAD

**Issue by thorrrr** [HandyHat/ha-hildebrandglow-dcc#257]
The problem
Energy Data no longer showing after 10 Oct after latest update. I could see it yesterday but after update 2022.10.3 it is missing and nothing is recording today?
Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.0
Frontend 20221010.0 - latest

What version of Home Assistant Core has the issue?
2022.10.3

What was the last working version of Home Assistant Core?
2022.10.2

What type of installation are you running?
Home Assistant Supervised

**Debug log**
Enable debug logging by following the instructions [here](https://github.com/HandyHat/ha-hildebrandglow-dcc#debugging)

**Additional context**
This error originated from a custom integration.

Logger: custom_components.hildebrandglow_dcc.glow
Source: custom_components/hildebrandglow_dcc/glow.py:194
Integration: Hildebrand Glow (DCC) (documentation, issues)
First occurred: 08:35:57 (1 occurrences)
Last logged: 08:35:57

Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/0328f32a-09c1-4769-8ffa-889d9313f86b/tariff)

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:515
First occurred: 08:35:55 (3 occurrences)
Last logged: 09:00:55

Update of sensor.gas_tariff_standing is taking over 10 seconds
Update of sensor.electric_tariff_standing is taking over 10 seconds

**Comment by craigrouse** [comment]
@thorrrr I don't believe this is an issue with the latest update, it's an ongoing issue on Hildebrand's end, and it manifests in HA by the sensors showing as unavailable periodically throughout the day. If you happen to restart and the next poll returns a 500 error, the sensors will show as unavailable until the next successful poll.

**Comment by matthew-t-watson** [comment]
Broken as well with 
'''
Glow response status code: 500 (https://api.glowmarkt.com/api/
'''

**Comment by a8ree** [comment]
I'm also seeing the same issue

**Comment by gnlgrim** [comment]
Good day .
Has anyone been able to fix the above issue. I am getting the exact same error.
Also I am only getting readings every hour instead of every 30min in my energy dashboard
Before. In September
![before](https://user-images.githubusercontent.com/88459189/196120593-453d744b-4292-47e5-9e2f-30a9aeeb130a.JPG)

After . Yesterday
![after](https://user-images.githubusercontent.com/88459189/196120601-ca31d159-be44-423c-b0d3-8a59ade3c6a1.JPG)

**Comment by thorrrr** [comment]
Same must be the API feed i guess to restrict data

**Comment by JohnMcLear** [comment]
My data stopped on the 23rd of Sep:
![image](https://user-images.githubusercontent.com/220864/196212850-742a3d07-975b-446a-823d-ff6c4c36963c.png)

I can still see the data in the bright mobile app.

Is this the same issue?

```
Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/REDACTED)
Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/REDACTED/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff4d6795d0>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by gnlgrim** [comment]
This has now become a occurring issue and I do not see any feedback from the contributors.
It would have been nice if someone would have said, we are working on it and should be resolved within ......
a bit disappointing.

**Comment by chopst1x** [comment]
> Good day . Has anyone been able to fix the above issue. I am getting the exact same error. Also I am only getting readings every hour instead of every 30min in my energy dashboard Before. In September ![before](https://user-images.githubusercontent.com/88459189/196120593-453d744b-4292-47e5-9e2f-30a9aeeb130a.JPG)
> 
> After . Yesterday ![after](https://user-images.githubusercontent.com/88459189/196120601-ca31d159-be44-423c-b0d3-8a59ade3c6a1.JPG)

I too have this issue since the 10th Oct. It is only showing every hour rather than 30min. Anyone know how to fix?

**Comment by HandyHat** [comment]
Hey all,
The issue here is that this integration is hitting rate limits imposed by Hildebrand as it is putting a lot of strain on their servers - the changes detailed in https://github.com/HandyHat/ha-hildebrandglow-dcc/discussions/191 should fix this, but this entails a full rewrite of the integration and thus is taking quite a while. PRs are always welcome!

**Comment by HandyHat** [comment]
These changes have been implemented in v1.0.0 of the integration, and so this should no longer occur. Please say if this persists!

**Comment by thorrrr** [comment]
Its been running on and off past few days and today stopped at 5am this morning !!!!!!
Was hoping 2023 would be better !!!!!

![image](https://user-images.githubusercontent.com/8170673/210179295-73447ac4-bc3f-4496-b8b8-215f08f77778.png)

**Comment by HandyHat** [comment]
Over the last few days there has been some API instability on the glow end. I've been running v1.0.0 all day today and it's been working well.

**Comment by JohnMcLear** [comment]
> Over the last few days there has been some API instability on the glow end. I've been running v1.0.0 all day today and it's been working well.

Thanks so much for all of your effort rewriting this.  If anyone can, now would be a great time to sponsor this project <3

**Comment by JohnMcLear** [comment]
After updating I had to change the Dashboard > Energy > Gas value to "DCC Sourced smart gas meter Usage (today)"..  The original entity was no longer available.

**Comment by JohnMcLear** [comment]
fwiw this hasn't worked since 3rd

**Comment by HandyHat** [comment]
@JohnMcLear As in you've stopped seeing data? Are there any errors in the log?

**Comment by JohnMcLear** [comment]
Yea nothing hitting HA at all (since 3rd), I see the values in bright app..

I searched for "glow" in logs but nothing exists.

Sorry for slow response and thanks for following up

**Comment by HandyHat** [comment]
@JohnMcLear how odd. Just to confirm, you are running `v1.0.2`? Is data still flowing in the Bright app?

**Comment by JohnMcLear** [comment]
``v1.0.3`` (just updated from ``v1.0.2``) and yea data is in Bright app, nothing in logs.  Should I enable verbose logging and report back?

**Comment by HandyHat** [comment]
Yes please! Feel free to open a new issue if it's easier :) @JohnMcLear

**Comment by JohnMcLear** [comment]
It's worked since 19th of Jan, no changes made...  *shrugs
