### ISSUE TITLE
Gas wrong Device class in HA 2022.11.1

### ISSUE THREAD

**Issue by ColinRobbins** [HandyHat/ha-hildebrandglow-dcc#264]
**Describe the bug**
HA 2022.11 introduced a breaking change.
Gas sensors need to be `DEVICE_CLASS_GAS` rather than `DEVICE_CLASS_ENERGY`
Otherwise they will not be available to the Energy integration.

**Comment by ColinRobbins** [comment]
Testing a fix...

**Comment by HandyHat** [comment]
The documentation (https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes) still indicates that if your sensor is in kWh, the device class should be energy, so I don't think this is the solution.

It looks like this is a bug in Home Assistant Core - https://github.com/home-assistant/core/issues/81496

**Comment by ColinRobbins** [comment]
Closed, see https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/266
