### ISSUE TITLE
HA 2022.11 - gas consumption data can't be added to the energy dashboard

### ISSUE THREAD

**Issue by HandyHat** [HandyHat/ha-hildebrandglow-dcc#266]
See #264 for more information

**Comment by dklemm** [comment]
I think the issue is with HA https://github.com/home-assistant/frontend/issues/14292

**Comment by Thorburn** [comment]
The Gas sensors need their State to be "Gas" not "Energy".

Using the following works for me to get the Gas Today readings in to the Energy tab.

`homeassistant:
    customize:
        sensor.gas_consumption_today:
          device_class: gas`

**Comment by dklemm** [comment]
> The Gas sensors need their State to be "Gas" not "Energy".
> 
> Using the following works for me to get the Gas Today readings in to the Energy tab.
> 
> `homeassistant: customize: sensor.gas_consumption_today: device_class: gas`

It might work to get the sensor added but its not the correct class.  device_class: gas is only valid for volume based measurements (m2 ft2), energy is the correct class for kwh etc.

**Comment by TomHBP** [comment]
I am also experiencing this issue. Loving this integration as it allows me to check up on things without having to use the appalling app from my energy provider, but having it on the energy dashboard would be the dream! Is this issue being actively worked on?

**Comment by purcell-lab** [comment]
This issue appears to be fixed in the 2022.12 beta release.

**Comment by STUKguy** [comment]
Not sure if mine is related but for some reason when i go to set up "Gas Consumption" under gas usage nothing shows up, but when i go to set up "Electricity grid" the gas option shows up on the consumed energy drop down

**Comment by HandyHat** [comment]
This should be fixed as of Home Assistant 2022.12 - if anyone if still having issues, please say!

**Comment by fhwi93ne** [comment]
Hi, I just updated to 2023.1.4 and have the same issue with my gas meter.
`state_class: total_increasing
unit_of_measurement: m³
device_class: gas
icon: mdi:gauge
friendly_name: Value`
So I gueds the issue still exists.

**Comment by HandyHat** [comment]
Hey @fhwi93ne, are you running v1.0.2?
I'm a bit confused because the `device_class` should be `electricity` and this integration has never set it to `gas`

**Comment by fhwi93ne** [comment]
Hi @HandyHat, v1.0.2 of what? My gas meter is based on an AI-on-the-edge-device. The sensors seem to look ok for me, but they do not show up in the energy dashboard. I cannot pick them as gas source. 
This is what MQTT-Discovery makes out of it:
`        {
          "device_class": null,
          "disabled_by": null,
          "disabled": false,
          "entity_category": null,
          "entity_id": "sensor.esp32_gaszaehler_value",
          "icon": null,
          "original_device_class": "gas",
          "original_icon": "mdi:gauge",
          "state": {
            "entity_id": "sensor.esp32_gaszaehler_value",
            "state": "23771.628",
            "attributes": {
              "state_class": "total_increasing",
              "unit_of_measurement": "m\u00b3",
              "device_class": "gas",
              "icon": "mdi:gauge",
              "friendly_name": "Value"
            },
            "last_changed": "2023-01-14T20:43:47.643966+00:00",
            "last_updated": "2023-01-14T20:43:47.643966+00:00"
          },
          "unit_of_measurement": "m\u00b3"
        },`

It looks basically the same as my Shelly based energy meters, just for gas.

**Comment by fhwi93ne** [comment]
@HandyHat, my fault. I posted in the wrong repo. This belongs to homeassistant itself. Sorry for that!

**Comment by HandyHat** [comment]
Ah, no worries!
