### ISSUE TITLE
Glow API load

### ISSUE THREAD

**Issue by ColinRobbins** [HandyHat/ha-hildebrandglow-dcc#267]
Part of the instability issue is the load on the Glow servers, from calculating the yearly totals.

In the Rest API spec, there is a *depricated* value called ‘currentMeterReading’.   

This is all we need for HA.

If Hildebrand were to reinstate the meter reading value, it would be relatively simple to rework this integration, to give everything the Energy integration needs (combined with the utility meter integration).

It would be a breaking change, but should relieve the server load considerably.
(Reduced the API calls in half - only need one call, not daily & yearly; the computation cost their end would be reduced).

Does anyone have good contact with Hildebrand to discuss this concept?

**Comment by HarvsG** [comment]
I sent this suggestion to Hildebrand and this is the reply I got. They asked me to post it here 

Thanks for bringing this confusion to our attention. For the record, the only segment of users who can access that functionality are people who have a Secure SMETS1 meter with our CAD connected and their meter has not been enrolled in the DCC. Unfortunately, as a DCC Other User we are not able to retrieve the Meter Read from the meter, it is not part of the restricted set of service requests we can make.

We've updated our swagger documentation based on the comment.

**Comment by 2e0byo** [comment]
Would it be worth simulating this anyhow?  We could get the current total (sum) and then simply poll the `/current` endpoint and do the maths ourself.  Only one api call would be needed, and with [`DataUpdateCoordinator`](https://developers.home-assistant.io/docs/integration_fetching_data/#coordinated-single-api-poll-for-data-for-all-entities) updating the individual sensors would be trivial.

It may also be possible at startup to work out what period we *don't* have data for and request a sum only of the missing data, but I don't know enough about HA's (sprawling) ecosystem to know how to do that, and I suspect the advantage would be pretty minimal---HA instances don't tend to restart very often.

**Comment by HandyHat** [comment]
Unfortunately as described here: https://docs.glowmarkt.com/GlowmarktAPIDataRetrievalDocumentationIndividualUserForBright.pdf
current consumption is not available via the DCC, as the data is always delayed by 30 mins.

The changes in #191 are the best way of simulating this I can think of and should reduce the load on the API. I am working hard on implementing them but it is taking a lot longer than expected 😅
