### ISSUE TITLE
Negative Electric Tariff Rate

### ISSUE THREAD

**Issue by Curtisjk** [HandyHat/ha-hildebrandglow-dcc#269]
I'm not sure since when this started happening - perhaps once my rate changed in October? But my rate and standing charge is appearing negative in HA:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/2105186/203386657-aa4aea4a-a38a-4f52-a1d3-849345c0925f.png">

Has anyone come across this before?

I think I only keep 2 weeks of data in HA (need to change this) and it's been negative for those 2 weeks.

**Comment by HandyHat** [comment]
Is it negative in the bright app?

**Comment by Curtisjk** [comment]
It is yes - sorry I should’ve checked that. I guess that means it’s an issue with the data feed from the meter?

Still getting billed positively unfortunately 😄

**Comment by HandyHat** [comment]
Yes, you'll need to contact your supplier to fix the data being supplied to "DCC Other Users" (Bright is one of these).
