### ISSUE TITLE
Energy dashboard reporting different to entity data?

### ISSUE THREAD

**Issue by hoppi05** [HandyHat/ha-hildebrandglow-dcc#272]
Hi all and first of all thanks for this great integration. I am also wondering if this is related to the previous report too? Here is what I am seeing. 

![Screenshot_20221130-063242_Home Assistant](https://user-images.githubusercontent.com/93948263/204725673-3a371912-cc40-4f23-bdde-8380b4e19609.png)
![Screenshot_20221130-063232_Home Assistant](https://user-images.githubusercontent.com/93948263/204725699-262ffda7-b494-4d45-9a26-bfbd5102dc5d.png)
![Screenshot_20221130-064045_Bright](https://user-images.githubusercontent.com/93948263/204725748-7b279fb7-51ef-45c6-82ec-12db1be6e89f.png)

As you can see the energy section shows the incorrect cost data? I have tried changing between the daily and yearly options but it does not resolve the issue? 

I added the electrical consumption (today) cost and this has a different value all together? 

Happy to get any logs if that would help? 

Regards
Hoppi

**Comment by Whizzykid** [comment]
I'm seeing the same thing too

**Comment by HandyHat** [comment]
This should be fixed as of v1.0.0

**Comment by hoppi05** [comment]
Thank you for looking into this and hopefully resolving, happy new year.
