### ISSUE TITLE
hildebrandglow-dcc fails to start on HA

### ISSUE THREAD

**Issue by adyoull** [HandyHat/ha-hildebrandglow-dcc#297]
**Describe the bug**
Setup failed for custom integration hildebrandglow_dcc: Requirements for hildebrandglow_dcc not found: ['https://github.com/cybermaggedon/pyglowmarkt/archive/69e9c949a3f0d0293ad1af4005de154b5de04234.zip#pyglowmarkt==0.5.4'].

**To Reproduce**
Steps to reproduce the behaviour:

**Comment by HandyHat** [comment]
Not sure why this is failing @adyoull but v1.0.3 changes pyglowmarkt to be installed from pypi. Please give it a go and hopefully it'll work!
