### ISSUE TITLE
Can't add integration

### ISSUE THREAD

**Issue by Peter-HVD** [HandyHat/ha-hildebrandglow-dcc#312]
**Describe the bug**
I have installed via HACS and restarted. When I go to Settings > Integrations > Add Integration I can select it from the list, but then get a window saying "Please wait, starting configuration wizard for Hildebrand Glow (DCC)" for about a minute which then ends with "Config flow could not be loaded: Unknown error"

**To Reproduce**
Steps to reproduce the behaviour:

go to Settings > Integrations > Add Integration and select it from the list

**Expected behaviour**
Configuration workflow should run

**Version**
2023.2.4 and the latest Hildebrand Glow (DCC)

**Debug log**
None

**Additional context**
None

**Comment by HandyHat** [comment]
Hey @Peter-HVD, if the config flow encounters an unknown error, it should log something as it is an exception. Can you confirm that logging is on (it's on by default) and that nothing was logged?

**Comment by StephenMilner** [comment]
Are you attempting to set up the integration from external to the HA network using a reverse proxy?

If so, you need to restart HA and do it via http not https on the local network address for HA

**Comment by Peter-HVD** [comment]
Hi. Sorry for not replying sooner. 

Although I had restarted HA a couple of times to see if that got it working working, as soon as I added the debug stuff to my config file and restarted, it worked! So I'm afraid that I can't be any more helpful.

Thanks all the same.

**Comment by HandyHat** [comment]
Happy to hear it's all working now!
