### ISSUE TITLE
Can't add repository https://github.com/HandyHat/ha-hildebrandglow-dcc

### ISSUE THREAD

**Issue by RobinE** [HandyHat/ha-hildebrandglow-dcc#321]
**Describe the bug**
Can't add repository https://github.com/HandyHat/ha-hildebrandglow-dcc

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to '.Settings/Add-ons.'
2. Click on 'ADD-ON-STORE'
3. Click on three dots (top right)
4. Click on 'Repositories'
5. in 'Manage add-on repositories' pane, enter 'https://github.com/HandyHat/ha-hildebrandglow-dcc'
6. Click on 'ADD'
7. See error 'https://github.com/HandyHat/ha-hildebrandglow-dcc is not a valid add-on repository'

**Expected behaviour**
Expected to see the Add-on loaded.

**Screenshots**

**Version**
v1.0.3
Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Frontend 20230309.1 - latest

**Additional context**
Current RaspberryPi  release, running on RPi 4 hardware, with local area connection to Chrome browser on a Mac system

**Comment by RobinE** [comment]
Error log shows:
2023-03-25 21:22:06.603 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store/repositories - https://github.com/HandyHat/ha-hildebrandglow-dcc is not a valid add-on repository

**Comment by HandyHat** [comment]
Hey @RobinE, this repository is a HACS default and thus does not need to be added. You can use the My Home Assistant link in the readme or just search for `Hildebrand Glow (DCC)` to find the integration.

**Comment by RobinE** [comment]
It was my sloppiness calling this an add-on. Sorry, I realised it was an integration.
What led me astray was that the default installation of HA on an RPi4 shows a list of 
"Home Assistant Community Add-ons" in the "ADD-ON-STORE" under the "Add-ons" selection in the "Settings" panel.
I guess this means a list of **Add-ons** available from  the "Home Assistant Community" (including HACS itself) rather than **integrations**. That section heading is likely to lead many another Newbie astray, (it's not your problem)
As you explained, one needs to install the **HACS add-on** as such before one can install this integration (and others).
     The Installation section of the README.md might make **requires the HACS Add-on** more clear.
After installing the HACS Add-on, everything went as it should. 
Your explanation solved my problem.  Many thanks for responding quickly.
