### ISSUE TITLE
The integration has stopped working since 1st April

### ISSUE THREAD

**Issue by Alf-Tupper** [HandyHat/ha-hildebrandglow-dcc#397]
Since the 1st of April, I only get an update around 1 am, and now it's not able to connect.

This error originated from a custom integration.

Logger: custom_components.hildebrandglow_dcc.sensor
Source: custom_components/hildebrandglow_dcc/sensor.py:168
integration: Hildebrand Glow (DCC) (documentation, issues)
First occurred: 18:05:02 (5 occurrences)
Last logged: 19:05:33

Cannot connect: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by frostaholic** [comment]
Mine did the same I guessed it was something to do with changing to BST.
I used the sensor.py from last BST seems to be working.

**Comment by Alf-Tupper** [comment]
This has also worked for me. The sensor values got updated as soon as HA restarted. Cheers @frostaholic
