### ISSUE TITLE
Incorrect Units for Standing Charge

### ISSUE THREAD

**Issue by ColinRobbins** [HandyHat/ha-hildebrandglow-dcc#53]
**Describe the bug**
The standing charge is shown as GBP/kWh.

**To Reproduce**
Run the integration, and view the sensor

**Expected behaviour**
Units should be GBP

**Version**
What version of the integration and what version of Home Assistant are you running?

5.0

**Comment by si458** [comment]
@HandyHat can the fix be implemented please?
