### ISSUE TITLE
1000s of DNS lookups to  api.glowmarkt.com

### ISSUE THREAD

**Issue by smithbill17** [HandyHat/ha-hildebrandglow-dcc#55]
I use Pi-hole (see https://pi-hole.net/) on my LAN to filter out excessive internet adverts and also as my DHCP & DNS lookup server.

Sometime after installing this integration, I noticed many 1000's of DNS lookups to  api.glowmarkt.com  in my Pi-hole dashboard. There are 30+ lookups every 1second.

To see these lookups, you would need to setup Pi-hole or some other network device to receive & forward DNS queries. I have attached a screenshot.

Surely 30+ DNS lookups every 1 second is unnecessary and presumably not good for LAN, ISP or Hildebrand servers!?

Home Assistant v2021.10.6
Hildebrand Glow (DCC) integration v0.5.0

![Screenshot_2021-10-27-12-59-34-366_com android chrome](https://user-images.githubusercontent.com/66825587/139063106-38f25526-78cf-4258-ba44-c4d1b4b010c2.jpg)

**Comment by ColinRobbins** [comment]
A potential resolution would be to use [requests-cache](https://pypi.org/project/requests-cache/).
But it worries me that no other HA integrations see the need to use it.

**Comment by xhemp** [comment]
Looks like after the network issue Glow had with their systems last week/weekend ( https://forum.glowmarkt.com/index.php?p=/discussion/comment/540#Comment_540 ), they just posted an update on their forum with the following:

```
UPDATE from the Glow team

Because some users without our CAD are calling the API much too frequently (it should be once per half hour) we have had to alter the way the call is dealt with and reject the excess traffic.

Most on this forum have our CAD so the point is moot but FYI, we've got a lot of Home Assistant users of MQTT. We tell people that MQTT isn't meant for half hourly data but they are using brokers that seem to make a lot of redundant calls.

We hope to get our usual more frequent updates of the DCC data in place soon but wanted to explain why we are currently on overnight only. Please bear with us and check back in a day or two. Thank you.
```

Checking my pi-hole, since yesterday I can see 11676 DNS queries (in less than 24 hours) which seems a bit excessive.
Is there anything we can do with regards to that?
Just asking as they are throttling the calls and I am not (and probably others) able to get info at all to HA.

**Comment by smithbill17** [comment]
Since 1st Feb, I seem to be only getting a single reading at 5-6am every 24hrs (which is obviously pretty useless). If we're still making 1000s of DNS queries every day, then surely the only way forward is to stop retrieving 6 data points every 2mins and instead retrieve the same data every 30mins?

**Comment by xhemp** [comment]
> @smithbill17 i just suggested this in another issue
> https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/126#issuecomment-1032600786

Nice, I haven't noticed that issue.
I've seen a scan_interval on glow.py, I changed from 2 minutes to 10 to test and it seems to work.

**Comment by si458** [comment]
> > @smithbill17 i just suggested this in another issue
> > [#126 (comment)](https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/126#issuecomment-1032600786)
> 
> Nice, I haven't noticed that issue. I've seen a scan_interval on glow.py, I changed from 2 minutes to 10 to test and it seems to work.

my fix should help the issue #135

**Comment by HandyHat** [comment]
Hey all, thanks for your work here. I agree - we are currently making too many calls to the Hildebrand API. I have got some suggestions on how to reduce this impact, and would love your feedback in the discussion: https://github.com/HandyHat/ha-hildebrandglow-dcc/discussions/191

**Comment by peter-dolkens** [comment]
Just to comment - the DNS queries are highly unlikely to be going anywhere near Hildebrand. Your API requests is a different discussion, which you already have underway, but the DNS requests should be cached in numerous places:

* The local system - most OSes will have some level of DNS cache
* The local router - most routers will set themselves as the DNS server, and forward requests to your configured DNS providers (or the ISP configured providers) - allowing for local network name resolution.
* Your upstream DNS servers - I can pretty much guarantee that your DNS queries are unlikely to be making it past your ISP / Cloudflare / Google / OpenDNS servers. Those servers will almost definitely be caching for the configured TTL. if not longer.
* Cascading DNS servers across the internet - If you somehow *do* manage to get past your configured upstream, then their configured upstream servers are also likely to be caching records.
* The domain registrar - It's unlikely that Hildebrand hosts its own nameservers. Far more likely is that they've given this job to Cloudflare, or Fastly, or Godaddy, or some other big name that is designed to serve immense amounts of DNS.

So we should definitely be careful to make sure that we're not making excessive DNS queries, but rest assured we're not DDoSing Hildebrand with this integration :)

**Comment by HandyHat** [comment]
v1.0.0 of the integration implements many of the ideas in #191 and should reduce the number of DNS lookups and the load on Hildebrand's servers. If you are still seeing excessive lookups, please say!
