### ISSUE TITLE
Stopped pulling data from Glow after switch to GMT

### ISSUE THREAD

**Issue by ColinRobbins** [HandyHat/ha-hildebrandglow-dcc#57]
**Describe the bug**
After the switch to GMT, the sensors have stopping pulling data from the Glow API, showing a data value of "0"

**To Reproduce**
Run the integration in the GMT timezone (UTC offset = 0)

**Expected behaviour**
Should retrieve data

**Version**
5.0

**Debug log**
Logs who the Glow API call fails.

**Comment by ColinRobbins** [comment]
Fixed with above pull request.

**Comment by adamlc** [comment]
I can confirm I'm having the same issue

**Comment by si458** [comment]
@adamlc ive made a repo with the attached fixes from @ColinRobbins so try adding my repo
https://github.com/si458/ha-hildebrandglow-dcc/tree/main

**Comment by si458** [comment]
@ColinRobbins for some mad reason the bright app and the api have stopped giving me data from my smart meters since about 2am this morning? is this the case for you?

**Comment by ColinRobbins** [comment]
Yes, no data here via API or Bright App.

**Comment by danfulton72** [comment]
It is the case for me!

**Comment by si458** [comment]
@ColinRobbins added a suggestion for a metric to show when last poll if intrested in trying to implement it?  #59

**Comment by si458** [comment]
@ColinRobbins reply from Bright via support email
```
Hello Simon,
As you are using our free Bright app without our CAD we have a limited ability to investigate.
It looks like we aren't able to get to your HAN which means the WAN is probably down.
This may recover overnight - if not, you will need to get onto your energy supplier as we have very little control as a DCC Other User
we can only read data and join a device to the HAN.
```

**Comment by ColinRobbins** [comment]
That sort of makes sense - when I looked at my Energy Provider supplied IHD this morning, the network icon was flashing, where it is normally solid, so could be a DCC issue.

**Comment by si458** [comment]
@ColinRobbins more good news :)
```
Thanks for flagging the issue
in fact it looks as though there was a change at the DCC that affected us but not all customers.
The Tech team are continuing to investigate
there was a backlog as a result and for those who were affected that is now being cleared.
Normal service should resume soon.
```

**Comment by si458** [comment]
my smart meter data has now all reappeared in the bright app
and also home assistant is now showing my data again,
although the is a huge 12 hour window gap but what can you do...

**Comment by ColinRobbins** [comment]
Mine too.
Although it shows a gap, the total will be correct.

**Comment by si458** [comment]
> Mine too. Although it shows a gap, the total will be correct.

ive just raised a question with there support that the `electricity.consumption.cost` resource might be incorrect
because ive just spotted the tariffs for myself being pulled from the api are different to what im actually being billed,
so the figures might be incorrect is they are doing the calculations for me and returning them via the api 😱

**Comment by danfulton72** [comment]
Yup, mine too.

**Comment by ColinRobbins** [comment]
Is the tarrif and cost data from Glow the same as the tariff and cost shown on your energy provider in-house-display?
Mine are the same (and both wrong).

There seems to be a frequent problem that the energy providers are  not pushing the correct and current tariff data to DCC.   If DCC is wrong, Glow will be wrong.

**Comment by si458** [comment]
Oh yeh my monitor shows the same prices the bright app show which is defo wrong haha

Gotta love technology! 

something so simple as changing a number is so difficult!

**Comment by HandyHat** [comment]
> who knew something so simple as changing a number is so difficult!

Bureaucracy at its finest!
