### ISSUE TITLE
add metric for last poll time

### ISSUE THREAD

**Issue by si458** [HandyHat/ha-hildebrandglow-dcc#59]
**Is your feature request related to a problem? Please describe.**
the is currently an issue with the API and retrieving data (about 2.30am it just stopped)

**Describe the solution you'd like**
a metric to show the last poll time of your smart meters,
so you can do something when the is an outage like a notification

**Describe alternatives you've considered**
checking the raw API directly shows the lasttime they polled your smart meter
```https://api.glowmarkt.com/api/v0-1/resource/{resourceId}/last-time```
```
{
  "status": "OK",
  "name": "electricity consumption",
  "resourceTypeId": "e3a5db34-6e0c-4221-9653-8d33e27511ba",
  "resourceId": "5dbf33f3-1410-4334-a703-a3f9ad645a93",
  "classifier": "electricity.consumption",
  "data": {
    "lastTs": 1635820200
  }
}
```

**Additional context**

**Comment by ColinRobbins** [comment]
That data is already available - see top right.

![1261B798-FF86-4221-91AC-6D9058E38F1B](https://user-images.githubusercontent.com/13466873/139849601-a463369c-3e53-496c-a384-2de7683c790b.jpeg)

**Comment by si458** [comment]
@ColinRobbins how do you do something on this though?
like if its not had any data in say 2 hours send a notification?

**Comment by ColinRobbins** [comment]
In the past, I have used a timer for that.
1) create an automation that triggers when the value changes.
2) in the automation start a timer helper.
3) if the value changes again, reset the timer.
4) if the timer expires, create a notification.
