### ISSUE TITLE
Entities units of measurement + more

### ISSUE THREAD

**Issue by robertalexa** [HandyHat/ha-hildebrandglow-dcc#88]
Hi @HandyHat and @ColinRobbins 

A few bits that i found wrong with the entities:
1. `sensor.electric_consumption_today` and `sensor.gas_consumption_today` are missing the unit of measurement (`kWh`) - this is in the graph
![image](https://user-images.githubusercontent.com/9019306/142902482-583de1b1-1057-419c-8ebb-4542a3020461.png)
![image](https://user-images.githubusercontent.com/9019306/142902517-a9f158f7-96ac-4010-a827-85903bcb7326.png)

2. same applies to `sensor.electric_consumption_year` and `sensor.gas_consumption_year`
![image](https://user-images.githubusercontent.com/9019306/142904196-cb3a8c6b-a855-459b-a0f3-3eed7305ce3e.png)
![image](https://user-images.githubusercontent.com/9019306/142904239-21067d81-2031-4a85-bd66-a608390fadbb.png)

3. `sensor.electric_cost_today` and `sensor.gas_cost_today` are missing the unit of measurement (currency as per instance setting?) - this is in the graph. This works fine for standing charge entities
![image](https://user-images.githubusercontent.com/9019306/142902712-ea53fe56-0256-478b-95f7-448152f90781.png)
![image](https://user-images.githubusercontent.com/9019306/142902741-6df1ed2c-90c3-4625-ace2-c747f79de73d.png)
![image](https://user-images.githubusercontent.com/9019306/142902961-ba567fc2-569d-451b-9b88-d3fec1741127.png)

4. `sensor.electric_consumption_year_cost` and `sensor.gas_consumption_year_cost`
4.1 have the wrong unit of measurement. For me the graph is showing `EUR`. This is not the case for standing charge. I must admit that i forgot to change my currency to `GBP` before installing the integration. Could this be the issue?
![image](https://user-images.githubusercontent.com/9019306/142903643-2d9df037-ead8-4679-997d-e3c6531d78f3.png)
![image](https://user-images.githubusercontent.com/9019306/142903659-d0dfc82b-4712-4304-9a09-2353d487772f.png)

4.2 Wouldn't the name `Electric Cost (Yearly)` be better? This will match `Electric Cost (Today)`
![image](https://user-images.githubusercontent.com/9019306/142904047-62e118b4-404c-46a0-b72b-738169ac50e8.png)

4.3 They do not have `unique_id`, so they can't be edited in HA - all the others are fine
![image](https://user-images.githubusercontent.com/9019306/142904000-5837dab0-899b-4acd-b466-ff354505d951.png)
![image](https://user-images.githubusercontent.com/9019306/142904083-c8bc87af-6503-44fb-aad7-ef5b8c3a73d6.png)

I am not sure if some of these were by design (or even limitations) or not, so please don't think i am throwing stones. But if they were not by design maybe they have just been overlooked. I know how it is when you stare at your own code for hours, you are starting to miss things.

Let me know if I can be of any further help

**Version**
What version of the integration and what version of Home Assistant are you running?
HA 2021.11.5
Integration v0.5.2

**Comment by robertalexa** [comment]
Thanks for taking the time to reply @ColinRobbins Much appreciated.

Would you suggest that i remove the integration and add it again? Are there any "leftovers" that i need to consider cleaning before the reinstall?

**Comment by ColinRobbins** [comment]
It depends how much you need any historic data in HA (across all integrations).
If you don’t need ANY history data, you could delete the Database, which has worked for me in the past.
… take this suggestion at your own risk, I am not a HA expert, and there maybe side effects I am now aware of in your  environment.

**Comment by robertalexa** [comment]
That would be a hard pass :)

I shall go have a play with this and report my findings.

**Comment by ColinRobbins** [comment]
I can’t track 4.3 down - everything in The DCC integration has a unique ID as far as I can see.
Is this sensor created by the HA energy/long term stats?

**Comment by robertalexa** [comment]
Right so I have reinstalled everything, got new sensors and set the up the energy as per our discussion on the HA forum.

Points 1 to 3 are still happening, and hopefully I am not misunderstanding them. What i mean is that the unit of measurement does not appear on the graph. But this might actually be a frontend issue because when i inspect the entities i can see the correct information. So possibly scrap this, issue might be with HA.
![image](https://user-images.githubusercontent.com/9019306/142917943-e03bb2fa-9e37-41e4-9524-e61d3bc6692a.png)

The entities at point 4 have not yet been recreated by the automation. I am guessing instead of being created at the time of the integration install, they get created further down the line?
![image](https://user-images.githubusercontent.com/9019306/142918139-9efd0b04-c7b1-4a09-9d7a-91edc38901a4.png)

So i can't validate my points above based on this. I will give it some more time for the entities to hopefully be created? I do not know for sure who created these entities, earlier they belonged to the meter devices, so i am guessing the integration does that rather than HA, but you would know this much better than me? If it is the integration, would it not be better for the entities to be created right from the get go, and have a value of 0 initially? Also, these entities are not mentioned in the Readme, making it even weirder:

![image](https://user-images.githubusercontent.com/9019306/142918567-cd81bb28-6ba5-47a0-a498-4a4964b9f43b.png)

But they are the entities which if renamed will create a breaking change, so i assume they belong to the integration indeed

**Comment by ColinRobbins** [comment]
The sensors you are showing here are the only ones created by this integration.
Any other sensors are created by the Energy integration.
They all have ‘unit_of_measurement’ set as far as I can see.
On my system the units show up in the graph too.

**Comment by robertalexa** [comment]
> Any other sensors are created by the Energy integration.

Right, i understand what you mean. Was not aware of that :)

Weird about the unit of measurement not showing on the graph. Not due to screen size or selected theme.

I will close this issue as it is clearly far off from what i first wrote. Should I discover more about the graph scale i will make sure to let you know.

Sorry to have wasted your time with this, i appreciate your help

**Comment by ColinRobbins** [comment]
No problem, and “no waste of time”, it all contributes to our understanding of how all this works!

**Comment by robertalexa** [comment]
Hey @ColinRobbins 

Just found another one, but can't figure out if this is an integration issue or a Frontend issue (i am inclined towards the Frontend)

If I add either `sensor.gas_tariff_rate` or `sensor.electric_tariff_rate` in a entities card in Lovelace, i get a console error (everytime the entity is loaded in the view)

![image](https://user-images.githubusercontent.com/9019306/143042268-5f5a7e94-faf1-4fae-80da-dbe8aa4c37ef.png)

I was wondering if this is happening at your end too?

**Comment by ColinRobbins** [comment]
Fixed by https://github.com/HandyHat/ha-hildebrandglow-dcc/pull/77
